apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cocoa
  namespace: argocd
spec:
  description: "Cocoa Loh Ya"
  sourceRepos:
    - "https://github.com/RaflyAdiyasa/cocoa-gitops"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
